version: '3'
services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - MONGO_URI=${MONGO_URI}
      - APP_CONTEXT=${APP_CONTEXT}
      - PORT=${PORT}
      - API_VERSION=${API_VERSION}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    command: npm start
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_URI_TEST=${MONGO_URI_TEST}
    ports:
      - '27017:27017'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
