version: '2'
services:
  web:
    container_name: store
    platform: linux/amd64
    build: .
    command: npm run start
    ports:
      - '1001:1001'
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: on-failure
    networks:
      - authentication_some-net
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/mainstack'
      APP_CONTEXT: '${APP_CONTEXT}'
      PORT: 1001
      API_VERSION: 'v1'
      JWT_SECRET: '${JWT_SECRET}'
      JWT_EXPIRES_IN: '30d'
      MONGO_URI_TEST: 'mongodb://mongodb:27017/mainstack_test'
  mongodb:
    image: mongo:latest
    networks:
      - authentication_some-net
    ports:
      - '27017:27017'
networks:
  authentication_some-net:
    external: false
